### ISSUE TITLE
Doesn't Paho now support ws(s):// protocol natively?

### ISSUE THREAD

**Issue by jakubholynet** [inventit/mqtt-websocket-java#8]
It seems the latest Paho supports websockets natively, see f.ex. https://github.com/eclipse/paho.mqtt.java/blob/78de39a52c7c6fef972e258bd58c17bcf9c36ba1/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttAsyncClient.java#L436

Is there thus any reason for this library to continue to exist?

**Comment by dbaba** [comment]
Thank you for the info.
I've confirmed that MqttAsyncClient.java contains WS and WSS support.

The Paho Java Client page mentioned it as well, https://eclipse.org/paho/clients/java/#

The project has finished the role. I'll update README soon.
