### ISSUE TITLE
MqttAsyncClient

### ISSUE THREAD

**Issue by iceberg1369** [inventit/mqtt-websocket-java#9]
Hello there,
since paho MqttAsyncClient supports wss, but I couldn't find any sample code. coulde you please post a sample code in README.md which works in android too?

**Comment by dbaba** [comment]
Hi, as long as I know, there's nothing special for `ws://` and `wss://` support in Paho's MqttAsyncClient. I mean sample code for urls using `tcp://` or other protocols should work when you replace them with `ws://` and/or `wss://` if the endpoint supports the protocols.
